spring:
  application:
    name: galaxy-cache
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    database: 0
    lettuce:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 8
        min-idle: 0
#  cache:
#    cache-names: saas-cache1
